#!/usr/bin/env python3
"""Runs-per-case sensitivity of the rival phi on Tier-3 cells.

Question: Tier-3 sampled 4 runs/case while Ding's public data has 2 runs/case.
The rival null's per-case preference is estimated from the OTHER runs
(LOO/LOPO): with 4 runs it pools 3 runs, with 2 runs it uses a single run.
Does phi~1.0 (mechanical saturation) survive when we restrict to 2 runs/case,
matching Ding's design? If phi drops toward Ding's 0.6-0.9, the regime
contrast is confounded with runs-per-case and must be conditioned in the
paper.

Design (fixed): for each of the 6 collected cells, take runs 0..R-1, keep
only the first 2 runs of each case (deterministic), rerun the full rival
decomposition (n_sim=1e5, bootstrap=1e4, seed 0; c_fixed=4 for gpqa,
mean_distinct for aime). Compare phi_2runs vs phi_4runs (canonical
tier3_kappa.json).

Inputs: /tmp/ac_work/pilot3_*.csv (regenerated by pilot_stability_tier3.py)
plus the tier3_to_samples CSV regeneration; committed jsonl under
data/sampled/tier3/. Output: results/tier3_kappa_r2.json.
"""
import json
import os
import subprocess
import sys

import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
 sys.path.insert(0, _HERE)
from kappa_tool import load # noqa: E402
from kappa_tool.decompose import Config, decompose # noqa: E402

ROOT = os.path.dirname(_HERE)
TIER3 = os.path.join(ROOT, "data", "sampled", "tier3")
TMP = "/tmp/ac_work"

CELLS = [
 ("tier3_qwen3.5-9b-ctx4k_gpqa.jsonl", "qwen3.5-9b-ctx4k", "gpqa_diamond", 4),
 ("tier3_gemma4:26b_gpqa.jsonl", "gemma4-26b", "gpqa_diamond", 4),
 ("tier3_qwen3.8:27b_gpqa.jsonl", "qwen3.8-27b", "gpqa_diamond", 4),
 ("tier3_qwen3.5:9b_aime.jsonl", "qwen3.5-9b", "aime", None),
 ("tier3_gemma4:26b_aime.jsonl", "gemma4-26b", "aime", None),
 ("tier3_qwen3.8:27b_aime.jsonl", "qwen3.8-27b", "aime", None),
 ("tier3_qwen3.5:122b_aime.jsonl", "qwen3.5-122b", "aime", None),
 ("tier3_qwen3.5:122b_gpqa.jsonl", "qwen3.5-122b", "gpqa_diamond", 4),
 ("tier3_gemma4:31b_gpqa.jsonl", "gemma4-31b", "gpqa_diamond", 4),
 ("tier3_gemma4:31b_aime.jsonl", "gemma4-31b", "aime", None),
]


def to_samples_csv(jsonl, model, benchmark):
 safe = model.replace(":", "-")
 out = os.path.join(TMP, f"pilot3_{safe}_{benchmark}.csv")
 if not os.path.exists(out):
 cmd = [sys.executable, os.path.join(_HERE, "tier3_to_samples.py"),
 "--input", os.path.join(TIER3, jsonl),
 "--output", out,
 "--model", model, "--benchmark", benchmark]
 subprocess.run(cmd, check=True)
 return out


def main(:
 canon = json.load(open(os.path.join(ROOT, "results", "tier3_kappa.json")))
 out = {"generated_by": "tier3_kappa_r2.py",
 "note": ("runs-per-case sensitivity of rival phi: keep first 2 "
 "runs/case (Ding design) vs canonical 4 runs/case; "
 "n_sim=1e5, bootstrap=1e4, seed 0"),
 "cells": {}}
 for jsonl, model, benchmark, cfix in CELLS:
 csv_path = to_samples_csv(jsonl, model, benchmark)
 df = load.load_samples(csv_path)
 pairs = df[["case_id", "run_id"]].drop_duplicates(
 pairs2 = (pairs.sort_values(["case_id", "run_id"])
 .groupby("case_id").head(2))
 df2 = df.merge(pairs2, on=["case_id", "run_id"])
 r2_path = os.path.join(TMP,
 f"r2_{model.replace(':', '-')}_{benchmark}.csv")
 df2.to_csv(r2_path, index=False)
 cfg = Config(seed=0, n_sim=100000, bootstrap=10000, c_fixed=cfix,
 c_gpqa=4)
 d = decompose(load.load_samples(r2_path), cfg, per_sample=True)
 label, row = next(iter(d["cells"].items())
 canon_row = canon["cells"].get(label, {})
 out["cells"][label] = {
 "phi_2runs": row["share_explained_mech"],
 "kappa_emp_2runs": row["kappa_empirical_subset"],
 "kappa_rival_2runs": row["kappa_rival_case"],
 "phi_4runs": canon_row.get("share_explained_mech"),
 "kappa_emp_4runs": canon_row.get("kappa_empirical_subset"),
 "n_runs_2runs": int(row["n_runs"]),
 }
 print(f"[r2] {label}: phi_2runs={row['share_explained_mech']:.3f} "
 f"vs phi_4runs={canon_row.get('share_explained_mech')}", flush=True)
 with open(os.path.join(ROOT, "results", "tier3_kappa_r2.json"),
 "w") as f:
 json.dump(out, f, indent=2, default=str)
 print("wrote results/tier3_kappa_r2.json")


if __name__ == "__main__":
 main(
